// react/src/components/Header.jsx
function Header() {
  return (
    <>
      <div className="bg-light sticky-top">
        <header className="d-flex flex-wrap justify-content-center py-2 mb-3 border-bottom">
          <p style={{ fontWeight: "bold", fontSize: "24px" }}>User Database</p>
        </header>
      </div>
    </>
  );
}

export default Header;

// vue/src/components/Header.vue
<script>
export default {
  name: 'HeaderComponent'
}
</script>

<template>
  <div className="bg-light sticky-top">
    <header className="d-flex flex-wrap justify-content-center py-2 mb-3 border-bottom">
      <p style="fontWeight: bold; fontSize: 24px">User Database</p>
    </header>
  </div>
</template>
